###     Properties for development     ###
##########################################
spring:
  profiles: dev
  h2.console:
    enabled: true
    path: /h2-console
  ###   DDL   ###
  jpa.hibernate.ddl-auto: update
  ###   DATASOURCES   ###
  ## You can override datasource by uncommented and fill these lines
  datasource:
    url: jdbc:mysql://localhost:3306/monitor
    driverClassName: com.mysql.jdbc.Driver
    username: MONITOR_DBA
    password: 7VOdT9eHInPJTueFjSfC


application:
  authentication:
    ### Security (ldap | database) ###
    provider: database
    ###   LDAP Authentication   ###
    # ldap:
    #  url:
    #  userSearchFilter:
    #  firstNameAttributName:
    #  lastNameAttributName:
    #  mailAttributName:
  ### Widgets Repo ###
  widgets.local.folderPath: C:\Users\F376354\Desktop\Stage\GIT\v2\widgets